### ISSUE TITLE
Reduce number of annotations

### ISSUE THREAD

**Issue by philwebb** [sbrannen/spring-composed#10]
It feels like currently there are too many `@RequestMapping` annotations making things a little hard to understand.

Perhaps it would be better to limit the scope and focus only on common REST idioms? You could have only `@Get`, `@Post`, `@Put` and `@Delete` annotations. All would produce `APPLICATION_JSON` by default (but provide a param to override). The `@ResponseStatus` defaults could be copied from the `...Resource` versions, again with an escape hatch if you want to override the response status.

**Comment by sbrannen** [comment]
@philwebb,

I agree: there are definitely too many `@RequestMapping` variants at the moment.

The current goal is to brainstorm, accepting numerous proposals for the time being, and then reduce the set of annotations officially supported by the Spring Framework when they get incorporated in Spring Framework 4.3.

I'll update the README to reflect this.

In the interim, feel free to voice your opinion on which annotations should make it into Spring in [SPR-13442](https://jira.spring.io/browse/SPR-13442).

Regarding `@Get`, `@Post`, `@Put`, and `@Delete`, we should keep those as _plain vanilla_ annotations that can be used with Spring MVC browser-based applications or REST applications. Thus I don't think it makes sense to default their behavior for REST use cases.

The general consensus amongst Spring developers I've spoken with is that we should not officially support annotations like `@GetJson`, `@PostXml`, etc. However, it would be nice to have predefined annotations that target REST applications. With that in mind, the current `@GetResource`, `@PostResource`, etc. might be well suited.

Thoughts?

Sam

**Comment by rstoyanchev** [comment]
+1 for plain vanilla and all else Sam said. 

Also wondering if the combination @RestController + @Get is sufficient to imply whatever @GetResource would -- in other words removing the need for a dedicated separate @GetResource annotation.

Also in JAX-RS the @Resource and @SubResource go along with a resource-centric URL structure whereas @Controller generally allows more flexibility. If we assume that meaning is well understood and established, it might be confusing to introduce our own "Resource" annotations that aren't anything like that.

Just food for thought..

**Comment by philwebb** [comment]
I like the idea of automatically returning a sensible response status for rest operations based on the HTTP method but it's a little unnerving to have `@Post` etc work differently when used on a `@RestController` vs `@Controller`.

Would having `@ResponseStatus` defaults on the annotations effect classic web application? Do you always want to return `200` from a `POST` or is `201` equally fine?

**Comment by rstoyanchev** [comment]
> it's a little unnerving to have @Post etc work differently when used on a @RestController vs @Controller

Point taken. That said having `@Get` and `@GetResource` nevertheless introduces two different semantics that need to be understood. The key question is what those additional semantics are and whether they're always desirable when using `@RestController`. If so then `@RestController` becomes a convenient way to "acquire" those additional semantics vs having to write `@GetResource` everywhere, much like it eliminated the need to have `@ResponseBody` everywhere.

**Comment by philwebb** [comment]
@rstoyanchev I think you're right, it's too much noise otherwise. 

We could add a new `@StandardResponseStatus` annotation that tells Spring to set the status based on the HTTP method. We could then add that as a meta-annotation to `@RestController`. The problem will be that it breaks back compatibility.

**Comment by sbrannen** [comment]
Although I really like the thought of having the response status automatically set to 201 if I'm using `@Post` and `@ResponseBody` (either directly or indirectly via `@RestController`), I'm afraid it's a no-go.

The key issue I have with any kind of _intelligent_ defaulting (for existing annotations, which may be composed by third parties) is that it will most certainly break backwards compatibility. Thus... we will simply have to avoid that.

With that in mind, the only feasible way to introduce intelligent defaulting for the response status is by doing something like @philwebb suggested: we can introduce a new annotation that enables _automatic response status detection_, perhaps something like `@StandardResponseStatus`, `@AutoResponseStatus`, `@DetectResponseStatus`, etc. But... I would not put that on `@RestController` (again due to backwards compatibility concerns).

Thoughts?

**Comment by sdeleuze** [comment]
What about a new `@RestController` attribute to enable this ?

**Comment by sbrannen** [comment]
@sdeleuze, that would be an option, but it would need to be _disabled_ by default (again, due to backwards compatibility issues).

However, in general, I would recommend against introducing behavior specific to a _composed annotation_ (like `@RestController`). By definition, composed annotations should _compose_ behavior from meta-annotations: they should _not_ have any behavior associated directly with them. In other words, we will likely never have code that directly looks up `@RestController`. Instead, as is the case now, we look up `@Controller`, `@Component`, and `@ResponseBody` (i.e., the constituent parts of `@RestController`).

With that principle in mind, we could introduce a general purpose feature via a new annotation like the aforementioned `@AutoResponseStatus`... but with an attribute that allows it to be enabled or disabled. In other words, `@AutoResponseStatus` should not just be a _marker annotation_. This would also allow `@RestController` to be meta-annotated with `@AutoResponseStatus` and to use `@AliasFor` to create an attribute override for the flag in `@AutoResponseStatus`.

Perhaps an example would make that more clear...

``` java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoResponseStatus {
    boolean value() default true;
}


@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Controller
@ResponseBody
@AutoResponseStatus
public @interface RestController {

    String value() default "";

    @AliasFor(annotation = AutoResponseStatus.class, attribute = "value")
    boolean autoResponseStatus() default false;
}
```

Thoughts?

**Comment by sdeleuze** [comment]
I like that :+1:

**Comment by sbrannen** [comment]
@rstoyanchev, what do you think about adding a feature like `@AutoResponseStatus` in Spring Framework 4.3?

**Comment by rstoyanchev** [comment]
It's worth running with the idea to see where it takes us.

If I understand correctly it's not the same as `@ResponseStatus` but rather alongside it, offering an alternative. If so we there is an opportunity to have slightly different semantics for example with regards to whether the method can override the status. Or in general how do you deviate from "auto" behavior is important. Otherwise auto becomes rigid and less useful.

The `@ResponseStatus` annotation is for any controller method -- response body or view resolution, as well as on exceptions, so it's a little hard to refine it's behavior. For once at the time we check for the annotation (e.g. in ServletInvocableHandlerMethod) we have no idea how the response will be rendered and therefore how to check for an override.

An `@AutoResponseStatus` however sounds like would target REST controller scenarios so it could apply specifically to `@ResponseBody` rendering where `ResponseEntity` could be used to override the status. But then again I might want to return a `ResponseEntity` because I want to add a header, not because I want to alter the auto response status. Also what's the effect of having `@ResponseStatus` on a controller that also has `@AutoResponseStatus`. Or what about all 3? So there are a few details to think through.

**Comment by philwebb** [comment]
I'm wondering if this should just be an attribute of `@ResponseBody` and not an additional annotation? Adding a new annotation seems to bring a lot of luggage, such as all questions @rstoyanchev raises above.

Perhaps something like:

``` java
// default
@ResponseBody(successStatus=ResponseBodyStatus.OK)

// auto
@ResponseBody(successStatus=ResponseBodyStatus.AUTO)
```

I'd definitely prefer an enum rather than a boolean.

**Comment by sbrannen** [comment]
I have raised [SPR-14006](https://jira.spring.io/browse/SPR-14006) and am therefore closing this issue.
