### ISSUE TITLE
Add annotations for common @Profile

### ISSUE THREAD

**Issue by sfussenegger** [sbrannen/spring-composed#15]
This might be somewhat of a reach but I felt I could bring it up here. We created annotations like `@ProductionBean` and `@DevelopmentConfiguration` for our internal projects and quite like them. 

This of course includes the definition of these common profiles which is the crux here. Maybe this opinionated approach to profiles is something for spring-boot rather than framework. For the latter it could be pretty handy though to control auto-configuration for unit tests or for standalone (no external dependencies) mode.

``` java
// not sure about the use of `${spring.profiles.development}` in `@Profile`
@Configuration
@Profile("${spring.profiles.development:development}")
@Retention(RUNTIME)
@Target(TYPE)
public @interface DevelopmentConfiguration {
}

@Configuration
@Profile("!${spring.profiles.development:development}")
@Retention(RUNTIME)
@Target(TYPE)
public static @interface NonDevelopmentConfiguration {
}
```

**Comment by sbrannen** [comment]
This is certainly an interesting idea, but you're right: it's beyond the scope of the core Spring Framework since it is directly coupled to profile names that are project-specific.

So I'll go ahead and close this issue, but feel free to discuss it directly with the [Spring Boot team](https://github.com/spring-projects/spring-boot/issues).
