### ISSUE TITLE
Alias for @RequestParam 

### ISSUE THREAD

**Issue by winterbe** [sbrannen/spring-composed#2]
I really like the idea of shorter annotations. Would like to also see aliases for other annotations like @RequestParam -> @Param

**Comment by sbrannen** [comment]
@winterbe, that's currently not possible for an annotation like `@RequestParam` since it it is declared with `@Target(ElementType.PARAMETER)`. Furthermore, Spring MVC looks up annotations on method parameters using `org.springframework.core.MethodParameter.getParameterAnnotations()` which (as of Spring Framework 4.2.1) does not support meta-annotations or composed annotations.

If you would like to see this support added, please create a [JIRA issue](https://jira.spring.io/secure/CreateIssue!default.jspa) for the Spring Framework.

Cheers,

Sam
